services:
  web:
    image: bklarson/calberry-web:0.0.2
    ports:
      - "80:3000"
    volumes:
      - ./web/data:/app/data
    restart: unless-stopped

  autohelm:
    image: bklarson/autohelm:0.0.2
    restart: unless-stopped
    environment:
      - COMPOSE_URL=https://raw.githubusercontent.com/bklarson/calberry/refs/heads/prod/docker-compose.yml
    volumes:
      - ./docker-compose.yml:/data/docker-compose.yml
      - /var/run/docker.sock:/var/run/docker.sock
